### PR TITLE
updated path to start jupyter script

### PR DESCRIPTION
**Pull request by aroraakshit**
updated path to start jupyter script based on 0.15 container: `0.15-cuda10.1-runtime-ubuntu18.04`

### CODE REVIEW

**Review by datametrician — APPROVED** [review]

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
Thanks for raising this @aroraakshit.

We specifically do not set the default service type to `LoadBalancer` as this would be an insecure default and in many cases would expose the Jupyter instance to the open internet. See the discussion on the [upstream chart here](dask/helm-chart/issues/53).

I think instead we need to document better the different ways of accessing the cluster. Currently we [output this to the terminal](https://github.com/rapidsai/helm-chart/blob/main/rapidsai/templates/NOTES.txt) when you install the chart, but perhaps a section in the README would also be useful.

I'm also a little confused that Jupyter is not starting for you. Setting the default args here is not the correct approach as it will start multiple copies of Jupyter, we already set the `JUPYTER_FG` [flag here](https://github.com/rapidsai/helm-chart/blob/bc10c7f71d9afe6c65bb0bc155206a00b5d7843d/rapidsai/values.yaml#L98-L99) which should start Jupyter in the foreground. This happens in the [Docker container here](https://github.com/rapidsai/docker/blob/060c109c8f70645707959633d58dd262f5862e3e/context/source_entrypoints/runtime_devel.sh#L5).

Perhaps there has been a regression in the Docker image? @ajschmidt8 do you have any thoughts?

**Comment by jacobtomlinson** [comment]
Did you install following [these instructions](https://github.com/rapidsai/helm-chart/blob/main/docs/csp.md)?

If so this is probably where we should set the default service type to `LoadBalancer`.

**Comment by ajschmidt8** [comment]
> Perhaps there has been a regression in the Docker image? @ajschmidt8 do you have any thoughts?

As far as I can tell, everything seems to be working correctly with our `0.15` images. I checked out `rapidsai/rapidsai:0.15-cuda10.1-runtime-ubuntu18.04` specifically to confirm and the jupyterlab server started up automatically both with and without the `-e JUPYTER_FG="true"` flag set.

**Comment by aroraakshit** [comment]
## Current docs/csp.md instructions tryout on GKE

Currently [these](https://github.com/rapidsai/helm-chart/blob/main/docs/csp.md#helm) instructions (at this step `helm install rapidstest rapidsai/rapidsai` result in (on GKE):
```
akshita@akshita-mlt ~ % kubectl get svc
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
kubernetes         ClusterIP      10.87.240.1     <none>          443/TCP        21m
rapidsai-jupyter   LoadBalancer   10.87.246.175   34.91.104.130   80:30801/TCP   9m31s
```
And
```
akshita@akshita-mlt ~ % kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
rapidsai-jupyter-76469d4494-lfcbw     0/1     CrashLoopBackOff   4          2m19s
rapidsai-scheduler-6bf96895b4-g67x7   1/1     Running            0          2m19s
rapidsai-worker-7c75c976b4-cx9jf      0/1     Completed          4          2m19s
rapidsai-worker-7c75c976b4-n5kqv      0/1     Completed          4          2m19s
rapidsai-worker-7c75c976b4-xhhcs      0/1     Completed          4          2m19s
```

and describe pod results in:
```
akshita@akshita-mlt ~ % kubectl describe pod rapidsai-jupyter-76469d4494-lfcbw
Name:         rapidsai-jupyter-76469d4494-lfcbw
Namespace:    default
Priority:     0
Node:         gke-rapids-default-pool-c007acfb-cjd5/10.164.0.42
Start Time:   Wed, 04 Nov 2020 15:34:32 -0800
Labels:       app=rapidsai
              component=jupyter
              pod-template-hash=76469d4494
              release=rapidstest
Annotations:  <none>
Status:       Running
IP:           10.84.1.10
IPs:
  IP:           10.84.1.10
Controlled By:  ReplicaSet/rapidsai-jupyter-76469d4494
Containers:
  rapidsai-jupyter:
    Container ID:  docker://337ab5a00223e082a38d36f8f09de334284893a44720e0cfac7e4cd15edbc23d
    Image:         rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04
    Image ID:      docker-pullable://rapidsai/rapidsai@sha256:92b1dbe5631c830ccdd29c3004aecbfcfa6b31ced188be3108565f316121f64b
    Port:          8888/TCP
    Host Port:     0/TCP
    Args:
      bash
      /rapids/notebooks/utils/start-jupyter.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    127
      Started:      Wed, 04 Nov 2020 15:40:19 -0800
      Finished:     Wed, 04 Nov 2020 15:40:19 -0800
    Ready:          False
    Restart Count:  6
    Limits:
      cpu:             2
      memory:          6G
      nvidia.com/gpu:  1
    Requests:
      cpu:             2
      memory:          6G
      nvidia.com/gpu:  1
    Environment:
      DASK_SCHEDULER_ADDRESS:             rapidsai-scheduler:8786
      DASK_DISTRIBUTED__DASHBOARD__LINK:  /proxy/rapidsai-scheduler:8787/status
    Mounts:
      /usr/local/etc/jupyter from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zz9b9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      rapidsai-jupyter-config
    Optional:  false
  default-token-zz9b9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zz9b9
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 nvidia.com/gpu=present:NoSchedule
                 nvidia.com/gpu:NoSchedule
Events:
  Type     Reason     Age                    From                                            Message
  ----     ------     ----                   ----                                            -------
  Normal   Scheduled  6m12s                  default-scheduler                               Successfully assigned default/rapidsai-jupyter-76469d4494-lfcbw to gke-rapids-default-pool-c007acfb-cjd5
  Normal   Pulled     4m42s (x5 over 6m12s)  kubelet, gke-rapids-default-pool-c007acfb-cjd5  Container image "rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04" already present on machine
  Normal   Created    4m42s (x5 over 6m11s)  kubelet, gke-rapids-default-pool-c007acfb-cjd5  Created container rapidsai-jupyter
  Normal   Started    4m42s (x5 over 6m11s)  kubelet, gke-rapids-default-pool-c007acfb-cjd5  Started container rapidsai-jupyter
  Warning  BackOff    63s (x24 over 6m9s)    kubelet, gke-rapids-default-pool-c007acfb-cjd5  Back-off restarting failed container
```

## Current README.md instructions tryout
[These](https://github.com/rapidsai/helm-chart#from-source) instructions.

`helm install rapidstest --namespace default rapidsai`
Able to launch the jupyter notebook and see the dask dashboard. But facing the following issue:
```
E1104 15:57:39.861061   54680 portforward.go:340] error creating error stream for port 8082 -> 8888: Timeout occured
Handling connection for 8082
E1104 15:57:40.027841   54680 portforward.go:340] error creating error stream for port 8082 -> 8888: Timeout occured
E1104 15:57:42.170445   54680 portforward.go:340] error creating error stream for port 8082 -> 8888: Timeout occured
Handling connection for 8082
Handling connection for 8082
E1104 15:58:09.866926   54680 portforward.go:340] error creating error stream for port 8082 -> 8888: Timeout occured
Handling connection for 8082
```
and 
```
Handling connection for 8083
E1104 16:26:31.996461   65943 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:8083->[::1]:60378: write tcp6 [::1]:8083->[::1]:60378: write: broken pipe
Handling connection for 8083
Handling connection for 8083
E1104 16:26:40.391965   65943 portforward.go:372] error copying from remote stream to local connection: readfrom tcp6 [::1]:8083->[::1]:60402: write tcp6 [::1]:8083->[::1]:60402: write: broken pipe
Handling connection for 8083
E1104 16:27:10.420161   65943 portforward.go:340] error creating error stream for port 8083 -> 8787: Timeout occured
Handling connection for 8083
```

that impacts, say a data upload from local machine to jupyterlab. Also jupyterlab works very slowly (restarting a notebook takes forever / launching a terminal never completes). Maybe because I am behind a VPN, not sure what's the cause.

## Specify jupyter serviceType as LoadBalancer in values.yml

Stable JupyterLab behavior. 

* Agree with you that we dont need to specify `args: ["bash", "/rapids/utils/start-jupyter.sh"]` since jupyterlab is already running. 
* Agree with you that specifying LoadBalancer as default would be insecure. 

**If we dont think any changes are needed based on the observations above, lets close this PR.**

**Comment by jacobtomlinson** [comment]
Ok it looks like we may just need a release if source builds are working for you. @ajschmidt8 would you be able to help with that?

Your port forwarding issues are strange. I think they are unrelated to the helm chart itself. But are likely a result of come VPN or GKE configuration. Regardless we should find a solution to this and document it. Would you mind raising a separate issue for that?

I'm going to close out this PR as suggested.

**Pull request closed without merging**
